language: php
dist: trusty
sudo: false
cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.1
  - 7.2

install: composer install

script: vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover ./build/logs/clover.xml